M48
; DRILL file {KiCad (6.0.7)} date Mon Mar 20 22:10:41 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-20T22:10:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X81.514Y-35.692
X81.615Y-133.98
X213.696Y-35.732
X213.823Y-134.067
T0
M30
