M48
; DRILL file {KiCad 7.0.7} date Fri Apr 12 20:50:54 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-12T20:50:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X82.987Y-42.982
X82.987Y-144.582
X165.537Y-42.982
X165.537Y-144.582
T0
M30
